next.config.ts, src/components/auth/LogoutButton.tsx
#6 
<br>
-  로그아웃 버튼 생성 및 테스트 완료
-  next.config 툴팁 설정 변경
<br>
> 작업한 내용 확인 및 체크
<br>
=> Feature/#6 auth signout - 로그아웃 버튼 생성

package.json, pnpm-lock.yaml, src/app/(pages)/profile/page.tsx, src/components/ProfileTabs.tsx, src/components/ui/Tabs.tsx
#29  #37 
<br>
탭 기초 컴포넌트 작성
프로필용 탭 컴포넌트 작성
<br>
<br>
> 작업한 내용 확인 및 체크
<br>
리뷰 예상 시간 1분
<br>
=> Feature/#37 tabs 컴포넌트

.prettierrc, package.json, pnpm-lock.yaml
<br>
prettier 설정 파일 생성
<br>
> 작업한 내용 확인 및 체크
<br>
빠른 리뷰 
<br>
=> init: prettiercc 생성

pnpm-lock.yaml, src/app/(pages)/post-create/page.tsx, src/components/post/PostCreateEdit.tsx, src/components/ui/daily.tsx, src/components/ui/shelter.tsx, src/lib/post.ts
> #46
> close #46 
<br>
> DB shelter, daily테이블에서 title, content 타입 동일하지않아 text로 설정해두었습니다(그 외 테이블 수정 더 필요할것같습니다 유저 위치 관련 등 좀 더 고민하고 공유해드리겠습니다)
주석은 안지웠습니다 참고하시고 주석들은 차후 취합 전 코드 리뷰 자료로 만들어서 공유해드리고 지우겠습니다
<br>
> https://github.com/user-attachments/assets/f19f60c9-0457-4153-a31e-837b3c6cf06f
<br>
> 작업한 내용 확인 및 체크
<br>
=> Feature/글제목,글작성칸, 조건부랜더링으로 카테고리별 작성칸 구현

src/components/landing/MapPreview.tsx
#71 
<br>
- 지오로케이션 사용해서 위치 기반 지도 표시
- 지도 미리보기 ui 개선
<br>
내 위치 허용 버튼 클릭 시 내 위치 중심으로 좌표 이동합니다
<br>
저희 집 주소 노출 이슈로 지도 이미지는 따로 첨부 안하겠습니다,,
<br>
작업한 내용 확인 및 체크
<br>
한 번씩 테스트 해보시기 바랍니다
<br>
=> Feature/#71 map preview: 내 위치 기반 지도 미리보기 표시

pnpm-lock.yaml
#85 
<br>
병합 오류 수정
<br>
<br>
작업한 내용 확인 및 체크
<br>
빠른 리뷰 필요 
<br>
=> hotfix: 패키지 병합 오류 수정 #85

next.config.ts, src/components/map/MainMap.tsx, src/components/map/ShelterDrawer.tsx, src/components/map/ShelterList.tsx, src/hooks/shelter/useShelters.ts, src/store/useMapStore.ts, src/store/useMarkerStore.ts
#122 
close #122 
<br>
대피소 리스트 지도 맵 마커 필터링 해서 리스트에 보이기
<br>
---
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> feat: 대피소 리스트 지도 맵 마커 필터링 기능 만들기

next.config.ts, src/components/community/PostCreateEdit.tsx, src/components/community/form/ImageDropzone.tsx, src/components/community/form/ShelterForm.tsx, src/lib/post.ts, src/supabase/imgBucket.ts
#82
#139 
<br>
작업한 내용 작성
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> feat: supabase에 커뮤니티 조건부 img넣기 및 로그인한 유저에 한해 업로드 가능 #82 #139

src/app/(pages)/map/[id]/page.tsx, src/app/api/fetchSheltersApi.ts, src/components/map/ShelterExtraFeature.tsx, src/types/shelter.ts
#131 #133 #134 #136 #137 
<br>
- 가공 데이터 추가
- 대피소 고유 id 파싱
- 3910000_S202400002 id로 이름만 렌더링해 정확한지 테스트
- 나머지 정보들도 렌더링
- 전화번호 필드 수정(예외처리)및 바로 전화 걸리게 만들기
- 지상지하구분/ 개방여부 데이터출력 값 변환 기존 (1/2 & Y/N)에서 유저 이해 가능하게
- 하단 행정안전부 콜센터도 전화 바로 가능하게 구현
- ExtraComponent에 props 넘겨서 주소데이터 받기
- 주소 트렁케이트 속성으로 한줄로 요약
- 유저 알림 토스트로 변경
- 나머지 데이터들도 예외처리(데이터가 undefined일 경우)
<br>
페이지 모습
복사 했을때
전화 걸었을때
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 5-10분
- 논의가 필요한 부분:  줄 바뀜이 일어나도 주소를 전부 표시할지 || 지금처럼 간소화 할 지
: 컴포넌트 이름 변경해야할 지
- 테스트 하실 분들은 코드 내에 id 및 URL 적어 뒀습니다!
<br>
=> [대피소디테일] 대피소정보 렌더링 및 추가 개선 완료

src/app/page.tsx, src/components/landing/AlertBanner.tsx, src/components/landing/BannerSection.tsx, src/components/landing/MapPreview.tsx, src/components/landing/NewsCard.tsx, src/components/layout/Header.tsx, src/components/map/UserGeolocationMap.tsx
#166 
<br>
- 지오로케이션 맵 컴포넌트에서 location에 null추가
- 지도 미리보기 전체 수정
- 나머지 섹션들 시안대로 전체 수정
- 하단 패딩 줘서 바텀 내브바에 가려지지 않게 수정
<br>
실제 모바일로 테스트 해본 화면(등록 URI가 아니라 지도 표시 안됨)
지도까지 표시 되는 화면
<br>
작업한 내용 확인 및 체크
<br>
배너 부분은 추후에 바뀔 수도 있습니다!
<br>
=> 랜딩페이지 디자인시안대로 수정

database.types.ts, package.json, pnpm-lock.yaml, src/app/(pages)/community-daily/page.tsx, src/app/(pages)/community-shelter/page.tsx, src/components/community/ShelterDetailPost.tsx, src/components/community/detail/DailyDetailPost.tsx, src/components/community/detail/ShelterDetailPost.tsx, src/hooks/community/useDailyPostDetailQuery.ts, src/supabase/getCommuniy.ts, src/utils/shelterPostDetailsQuery.tsx
<br>
수파베이스 테이블 수정내용(users테이블에서 profile_img열 삭제)이 코드에 제대로 반영되지 않아 페이지 렌더링과 
<br>신규유저 로그인이 불가능하게 된 에러를 해결
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> bugfix: 수파베이스 타입 관련 에러 해결

src/components/community/PostCreateEdit.tsx
close#192
<br>
빌드테스트 오류수정했습니다
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> [HotFix]: post-create 파트 build test

src/components/auth/SocialLoginButtons.tsx
=> 배포후 소셜로그인 테스트 코드 수정

src/app/(pages)/community-daily/page.tsx, src/app/(pages)/community-shelter/page.tsx, src/components/community/SearchBarToggle.tsx, src/components/community/detail/DailyDetailPost.tsx, src/components/community/detail/DailyPostButtons.tsx, src/components/community/detail/ShelterDetailPost.tsx, src/components/community/detail/ShelterPostButton.tsx
#205 
<br>
이전 일상 & 대피소 디자인 반영 PR을 올린 후, 레이아웃이 잘 못 렌더링 되던 이슈를 해결하였습니다.
- 유용해요 버튼 기능 구현
- 일상 & 대피소 게시글 상세 페이지 디자인 시안 적용
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> Style/fix 잘못 렌더링된 레이아웃 수정

src/components/community/PostCreateEdit.tsx, src/components/community/form/DailyForm.tsx, src/components/community/form/ShelterForm.tsx
#232 
<br>
일상 글 등록 오류 고침 및 붐빔 탭 삭제
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 10초
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> refactor: 일상 글 등록 오류 고침 및 붐빔 탭 삭제

src/components/community/PostCreateEdit.tsx
#235
<br>
착오가 있어서 enum코드 간단히 수정했습니다
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간:  3초
<br>
=> refactor: 코드 간단 수정 #235

src/app/(pages)/community-daily/page.tsx, src/app/(pages)/community-shelter/page.tsx, src/app/api/fetchSheltersApi.ts, src/components/auth/SocialLoginButtons.tsx, src/components/profile/ProfileEditPop.tsx
#228 #231 #237 #238
<br>
- 소셜로그인 드로어 시안대로 수정(아이콘 포함)
- 대피소 api가공: 대피소가 아닌 데이터 필터링 추가
- 프로필 수정 팝오버 닫기 기능 구현
- 커뮤니티 페이지 하단 패딩 적용
- 자잘한 것들 전부 수정했습니다
<br>
작업한 내용 확인 및 체크
<br>
<br>
=> Refactor: 일부 기능 리팩토링

database.types.ts, src/components/community/PostCreateEdit.tsx, src/components/community/form/ImageDropzone.tsx, src/components/community/form/ShelterForm.tsx, src/components/ui/BackButton.tsx
#234 
<br>
images테이블에 사진 넣기 구현 및 일상 게시글 DB오류 수정 layout 약간의 수정
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> refactor: 사진 입력 구현, 일상 게시글 오류 수정, 스타일 수정 #234

src/app/(pages)/community-daily/page.tsx, src/components/community/detail/DailyDetailPost.tsx, src/components/community/detail/ShelterDetailPost.tsx, src/store/useShelterStore.ts, src/supabase/imgBucket.ts, src/supabase/server.ts
=> hotfix:불필요한 디버깅 코드제거 및 에러처리 추가

middleware.ts, src/components/community/PostCreateEdit.tsx, src/components/community/form/DailyForm.tsx, src/components/community/form/ShelterForm.tsx
close#252
<br>
팀원이 체크해준 로그인 유지(새로고침시 팅김 발생)사항 수정 , UI시안에 맞게 디자인 수정
// 미들웨어(아직 미사용)
미리보기중 
- 빨간색 부분 - 입력할곳 입력하면 버튼 색 on, 혼잡도, 위생상태 버튼 클릭, hover, 일반 상태 색상 다르게 설정
- 파란색 부분 - 입력할곳 전부 안할시 버튼색 off
- 그 외 입력창 색상 grey계열로 수정
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 1분
- 고민 사항 작성: 
- 논의가 필요한 부분: 
<br>
=> feat: 로그인 유지 구현 및 시안에 맞는 UI수정 #252

src/components/community/PostCreateEdit.tsx
#267
<br>
미들웨어 구현하여 로그인 유지(새로고침시 팅김현상 수정), 시안에 따라 반응형 구현
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> style: 미들웨어 사용, 시안대로 반응형

package.json, pnpm-lock.yaml, src/components/map/MainMap.tsx
#282 
<br>
- 필터링 로직 usecallback() 으로 메모이제이션 
- 지도 기본 확대 함수 제거 및 사용자 터치 or 마우스 위치로 확대 되는 로직 추가하여 기존 충청도로만 확대 되는 문제 해결
- 클러스터 클릭 이벤트 수정 (확대 레벨 추가)
- 클러스터 최소 확대 레벨 7로 줄여서 주변 대피소 찾기 더욱 용이하게 수정
- 지도 스크롤 및 확대 시 디바운싱 적용하여 불필요한 필터링 및 리렌더링 제거
로딩속도 개선 결과 :
- 기존 지도 로딩속도 5초 => 1.5초 이내로 대폭 향상
<br>
기존 로딩속도
개선 로딩속도
<br>
작업한 내용 확인 및 체크
<br>
추가 개선해야 할 부분 있으면 알려주세요!
<br>
=> 지도 페이지 전체적 성능 개선 및 오류 수정

src/components/map/CrosshairButton.tsx, src/components/map/ShelterDrawer.tsx, src/components/map/ZoomControl.tsx
#302 
close #302
<br>
Image svg를 임포트해서 src에 붙이기
<br>
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> Refactor: Next/Image svg 사용 방식 변경 

README.md, src/components/profile/BlankPost.tsx, src/components/profile/CommentPost.tsx, src/components/profile/HelpfulPost.tsx, src/components/profile/WrittenPost.tsx
close #307 
<br>
- README 수정 
- 이미지 로드 방식을 import로 변경
- 참여한 게시글 (유용해요한 게시글)이 없을 때 보일 내용 추가
<br>
<br>
작업한 내용 확인 및 체크
<br>
오류가 있다면 연락 바람
<br>
=> Docs/#readme 수정 

src/app/page.tsx, src/components/landing/AlertBanner.tsx, src/components/landing/BannerSection.tsx, src/components/landing/MapPreview.tsx
#306 
<br>
- 랜딩페이지 및 랜딩관련 컴포넌트 퍼블릭 이미지 파일들 import 방식으로 전체 수정
- 알림 배너 레이아웃 수정
<br>
작업한 내용 확인 및 체크
<br>
- 리뷰 예상 시간: 
- 고민 사항 작성:
- 논의가 필요한 부분:
<br>
=> Refactor: 랜딩페이지 이미지 경로 변경 

src/app/layout.tsx
<br>
바뀐 도메인을 metadata(오픈 그래프)에 적용
<br>
<br>
작업한 내용 확인 및 체크
<br>
<br>
=> fix: 바뀐 도메인 적용

README.md, src/app/layout.tsx
=> Hotfix: main 병합

src/app/action/fetchDisasterAlert.ts, src/app/action/fetchNewsApi.ts
=> api 데이터 최신화
